#version 150
#extension GL_ARB_shader_bit_encoding : require
#define INTERSTELLAR_CLOUD_QUADS
#define INTERSTELLAR_SPLIT_MOVING
#define INTERSTELLAR_NATIVE_MESH
#define INTERSTELLAR_QUAD_MESH
#define INTERSTELLAR_MATERIALS
#define INTERSTELLAR_COMPACT_NODES
#define INTERSTELLAR_LIVE_DEFAULTS
#define INTERSTELLAR_VARIABLE_CHORD
#define INTERSTELLAR_SPLIT_AA
#define INTERSTELLAR_STREAMED_LAYOUT
#moj_import <interstellar:terrain_shared.glsl>
